# Generated by Django 5.1.7 on 2025-03-18 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefa',
            name='Titulo_Tarefa',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='data_limite',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='descricao',
            field=models.TextField(),
        ),
    ]
